/**:
  ros__parameters:
    wheel_radius: 0.336
    wheel_width: 0.235
    wheel_base: 2.875 # between front wheel center and rear wheel center
    wheel_tread: 1.64 # between left wheel center and right wheel center
    front_overhang: 0.84 # between front wheel center and vehicle front
    rear_overhang: 0.98 # between rear wheel center and vehicle rear
    left_overhang: 0.265 # between left wheel center and vehicle left
    right_overhang: 0.265 # between right wheel center and vehicle right
    vehicle_height: 1.430
    max_steer_angle: 0.699999988079071 # [rad]
    ####max_steer_angle: 0.610865 # [rad]

#tesla model 3